export const SAVE_QUIZ_REQUEST = 'SAVE_QUIZ_REQUEST';
export const FETCH_QUIZ_REQUEST = 'FETCH_QUIZ_REQUEST';
export const UPDATE_QUIZ_REQUEST = 'UPDATE_QUIZ_REQUEST';
export const DELETE_QUIZ_REQUEST = 'DELETE_QUIZ_REQUEST';
export const QUIZ_SUCCESS = 'QUIZ_SUCCESS';
export const QUIZ_FAILURE = 'QUIZ_FAILURE';